app:
  port: 8082
  logging:
    level: INFO
  datasource:
    driver: postgres
    host: localhost
    port: 5432
    database: email_notification_db_test
    username: email_notification_db_user
    password: secret
    logLevel: INFO
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrapServers: localhost:9092
  configs:
    batch: