app:
  port: 8082
  logging:
    level: INFO
  datasource:
    driver: postgres
    host: localhost
    port: 5432
    database: email_notification_db_test
    username: email_notification_db_user
    password: secret
    logLevel: INFO
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrapServers: localhost:9092
    clientId: email-notification-internal-client
    admin:
      topics:
        - name: c1.email.email-sending-request
          partitions: 1
          replicaFactor: 1
          retention: 72h
    producer:
      eventMappings:
        EmailRequestSendingEvent:
          topicName: c1.email.email-sending-request
          transactional: false
          disable: false