FROM golang:1.23-alpine AS builder
ARG BUILD_VERSION
ARG BUILD_COMMIT_HASH
ARG BUILD_TIME
ARG BS_PKG=github.com/KhaiHust/email-notification-service/worker/bootstrap
ENV GO111MODULE=on
COPY ./src /go/src
WORKDIR /go/src/worker
RUN cd /go/src/worker && go mod tidy
RUN env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ./worker \
    -ldflags="-X '$BS_PKG.Version=$BUILD_VERSION' -X '$BS_PKG.CommitHash=$BUILD_COMMIT_HASH' -X '$BS_PKG.BuildTime=$BUILD_TIME'"

FROM alpine:3.19
COPY --from=builder /go/src/worker/config /app/config
COPY --from=builder /go/src/worker/worker /app/worker
EXPOSE 8080
WORKDIR /app
RUN chmod +x ./worker
CMD ["./worker"]