FROM golang:1.23-alpine AS builder
ARG BUILD_VERSION
ARG BUILD_COMMIT_HASH
ARG BUILD_TIME
ARG BS_PKG=github.com/KhaiHust/email-notification-service/internal/bootstrap
ENV GO111MODULE=on
RUN apk add --no-cache git
COPY ./src /go/src
WORKDIR /go/src/internal
RUN cd /go/src/internal && go mod tidy
RUN env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ./internal \
    -ldflags="-X ${BS_PKG}.Version=${BUILD_VERSION} -X ${BS_PKG}.CommitHash=${BUILD_COMMIT_HASH} -X ${BS_PKG}.BuildTime=${BUILD_TIME}"

FROM alpine:3.19
COPY --from=builder /go/src/internal/config /app/config
COPY --from=builder /go/src/internal/resource/__files /app/resource/__files
COPY --from=builder /go/src/internal/internal /app/internal
EXPOSE 8080
WORKDIR /app
RUN chmod +x ./internal
CMD ["./internal"]