FROM golang:1.23-alpine AS builder
ARG BUILD_VERSION
ARG BUILD_COMMIT_HASH
ARG BUILD_TIME
ARG BS_PKG=github.com/KhaiHust/email-notification-service/migration/bootstrap
ENV GO111MODULE=on
COPY ./src /go/src
WORKDIR /go/src/migration
RUN cd /go/src/migration && go mod tidy
RUN env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ./migration \
    -ldflags="-X '$BS_PKG.Version=$BUILD_VERSION' -X '$BS_PKG.CommitHash=$BUILD_COMMIT_HASH' -X '$BS_PKG.BuildTime=$BUILD_TIME'"

FROM alpine:3.19
COPY --from=builder /go/src/migration/config /app/config
COPY --from=builder /go/src/migration/migrations /app/migrations
COPY --from=builder /go/src/migration/migration /app/migration
EXPOSE 8080
WORKDIR /app
RUN chmod +x ./migration
CMD ["./migration"]