app:
  port: 8081
  logging:
    development: true
  datasource:
    driver: postgres
    host: localhost
    port: 5432
    database: email_notification_db_test
    username: email_notification_db_user
    password: secret
  redis:
    host: localhost
    port: 6379

  services:
    provider:
      gmail:
        BaseOAuthUrl: https://accounts.google.com/o/oauth2/auth
        ClientId: ${GMAIL_CLIENT_ID}
        ClientSecret: ${GMAIL_CLIENT_SECRET}
        Scopes: "https://www.googleapis.com/auth/userinfo.email https://mail.google.com/"
        ResponseType: code
        RedirectUri: ${GMAIL_REDIRECT_URI}
        AccessType: offline

  kafka:
    bootstrapServers: localhost:9092
    clientId: email-notification-worker
    admin:
      topics:
        - name: c1.email.email-request-sync
          partitions: 1
          replicaFactor: 1
          retention: 72h
    producer:
      eventMappings:
        EmailRequestSyncEvent:
          topicName: c1.email.email-request-sync
          transactional: false
          disable: false
    consumer:
      handlerMappings:
        EmailSendingRequestHandler:
          topic: c1.email.email-sending-request
          groupId: c1.email.email-sending-request.EmailSendingRequestHandler.local
          enable: true
        EmailRequestSyncHandler:
          topic: c1.email.email-request-sync
          groupId: c1.email.email-request-sync.EmailRequestSyncHandler.local
          enable: true