package constant

const (
	QueryParamLimit            = "limit"
	QueryParamOffset           = "offset"
	QueryParamSortBy           = "sort_by"
	QueryParamSortOrder        = "sort_order"
	QueryParamSince            = "since"
	QueryParamUntil            = "until"
	QueryParamCreatedAtFrom    = "created_at_from"
	QueryParamCreatedAtTo      = "created_at_to"
	QueryParamUpdatedAtFrom    = "updated_at_from"
	QueryParamUpdatedAtTo      = "updated_at_to"
	QueryParamSentAtFrom       = "sent_at_from"
	QueryParamSentAtTo         = "sent_at_to"
	QueryParamErStatuses       = "er_statuses"
	QueryParamErCreatedAtFrom  = "er_created_at_from"
	QueryParamErCreatedAtTo    = "er_created_at_to"
	QueryParamErSentAtFrom     = "er_sent_at_from"
	QueryParamErSentAtTo       = "er_sent_at_to"
	QueryParamName             = "name"
	QueryParamEnvironment      = "environment"
	QueryParamTrackingID       = "tracking_id"
	QueryParamStartDate        = "start_date"
	QueryParamEndDate          = "end_date"
	QueryParamInterval         = "interval"
	QueryParamIsChart          = "is_chart"
	QueryParamDuration         = "duration"
	QueryParamProvider         = "provider"
	QueryParamRequestID        = "request_id"
	QueryRecipientEmail        = "recipient_email"
	QueryParamEmailTemplateIDs = "email_template_ids"
)
