app:
  datasource:
    driver: postgres
    host: localhost
    port: 5432
    database: email_notification_db_test
    username: email_notification_db_user
    password: secret
    migrationSource: file://migrations
  logging:
    development: true