app:
  name: Email Notification Service Public
  path: /email-notification-public
  security.jwt.type: JWT_TOKEN_MOBILE
  security:
      http:
        publicUrls:
          - /actuator/health
          - /actuator/info
          - /swagger/*
          - /v1/auth/login
          - /v1/auth/signup
          - /v1/auth/refresh-token
          - /v1/integrations/*
        protectedUrls:
          - { urlPattern: "/v1/workspaces/*", method: POST, roles: [ "MOBILE_APP" ], unauthorizedWwwAuthenticateHeaders: [ "Bearer" ] }
          - { urlPattern: "/v1/workspaces/*", method: GET, roles: [ "MOBILE_APP" ], unauthorizedWwwAuthenticateHeaders: [ "Bearer" ] }
          - { urlPattern: "/v1/workspaces/.*/providers/.*/oauth", method: POST, roles: [ "MOBILE_APP" ], unauthorizedWwwAuthenticateHeaders: [ "Bearer" ] }
          - { urlPattern: "/v1/workspaces/.*/providers/.*", method: GET, roles: [ "MOBILE_APP" ], unauthorizedWwwAuthenticateHeaders: [ "Bearer" ] }
          - { urlPattern: "/v1/workspaces/.*/templates", method: POST, roles: [ "MOBILE_APP" ], unauthorizedWwwAuthenticateHeaders: [ "Bearer" ] }
          - { urlPattern: "/v1/workspaces/.*/templates", method: GET, roles: [ "MOBILE_APP" ], unauthorizedWwwAuthenticateHeaders: [ "Bearer" ] }
          - { urlPattern: "/v1/workspaces/.*/send", method: POST, roles: [ "MOBILE_APP" ], unauthorizedWwwAuthenticateHeaders: [ "Bearer" ] }
