app:
  logging:
    development: true
  datasource:
    driver: postgres
    host: localhost
    port: 5432
    database: email_notification_db_test
    username: email_notification_db_user
    password: secret
  redis:
    host: localhost
    port: 6379
  security:
    http:
      jwt.publicKey: ${JWT_PUBLIC_KEY}
  services:
    provider:
      gmail:
        BaseOAuthUrl: https://accounts.google.com/o/oauth2/auth
        ClientId: ${GMAIL_CLIENT_ID}
        ClientSecret: ${GMAIL_CLIENT_SECRET}
        Scopes: "https://www.googleapis.com/auth/userinfo.email https://mail.google.com/"
        ResponseType: code
        RedirectUri: ${GMAIL_REDIRECT_URI}
        AccessType: "offline"
    auth:
        jwt:
          PrivateKey: ${JWT_PRIVATE_KEY}
          ExpiredAccessToken: 3600
          ExpiredRefreshToken: 604800

