app:
  logging:
    level: INFO
  datasource:
    driver: postgres
    host: localhost
    port: 5432
    database: email_notification_db_test
    username: email_notification_db_user
    password: secret
    logLevel: INFO
  redis:
    host: localhost
    port: 6379
  security:
    http:
      jwt.publicKey: ${JWT_PUBLIC_KEY}
  kafka:
    bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS}
    clientId: ccloud-go-client-ea58e09f-4481-471f-81e1-9464c8954ac2
    securityProtocol: SASL_SSL
    sasl:
        mechanism: PLAIN
        username: ${KAFKA_USERNAME}
        password: ${KAFKA_PASSWORD}
    admin:
      topics:
        - name: c1.email.email-sending-request
          partitions: 1
          replicaFactor: 1
          retention: 72h
    producer:
      eventMappings:
        EmailRequestSendingEvent:
          topicName: c1.email.email-sending-request
          transactional: false
          disable: false
        EmailRequestSyncEvent:
          topicName: c1.email.email-request-sync
          transactional: false
          disable: false
  services:
    provider:
      gmail:
        BaseOAuthUrl: https://accounts.google.com/o/oauth2/auth
        ClientId: ${GMAIL_CLIENT_ID}
        ClientSecret: ${GMAIL_CLIENT_SECRET}
        Scopes: "https://www.googleapis.com/auth/userinfo.email https://mail.google.com/"
        ResponseType: code
        RedirectUri: ${GMAIL_REDIRECT_URI}
        AccessType: "offline"
      outlook:
        BaseOAuthUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
        ClientId: ${OUTLOOK_CLIENT_ID}
        ClientSecret: ${OUTLOOK_CLIENT_SECRET}
        Scopes: "Mail.Send SMTP.Send User.Read offline_access"
        ResponseType: code
        RedirectUri: ${OUTLOOK_REDIRECT_URI}
        AccessType: "offline"
        TokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
    auth:
        jwt:
          PrivateKey: ${JWT_PRIVATE_KEY}
          PublicKey: ${JWT_PUBLIC_KEY}
          ExpiredAccessToken: 3600
          ExpiredRefreshToken: 604800
    encrypt:
      EncryptKey: "dGVzdF9lbmNyeXB0X2tleQ=="
      EncryptVersionTemplate: "dGVzdF9lbmNyeXB0X2tleQ=="
      EncryptTrackingIDKey: "dGVzdF9lbmNyeXB0X2tleQ=="
      EncryptDataEmailRequestKey: "dGVzdF9lbmNyeXB0X2tleQ=="
      EncryptTokenProviderKey: "dGVzdF9lbmNyeXB0X2tleQ=="
    newrelic:
      LicenseKey: ${NEW_RELIC_LICENSE_KEY}
      AppName: "email-notification-service-public"
      Enabled: true
