app:
  logging:
    development: true
  datasource:
    driver: postgres
    host: localhost
    port: 5432
    database: email_notification_db_test
    username: email_notification_db_user
    password: secret
  redis:
    host: localhost
    port: 6379

  services:
    provider:
      gmail:
        BaseOAuthUrl: https://accounts.google.com/o/oauth2/auth
        ClientId: ${GMAIL_CLIENT_ID}
        ClientSecret: ${GMAIL_CLIENT_SECRET}
        Scope: https://mail.google.com/
        ResponseType: code
        RedirectUri: ${GMAIL_REDIRECT_URI}
        AccessType: offline

