name: Build and Push Docker Images

on:
  push:
    branches:
      - master
      - feature/**
      - release/**

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_TAG: ${{ github.sha }}
  SERVICES: |
    internal
    worker
    public
    migration

jobs:
  build-and-push-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker asia-east1-docker.pkg.dev --quiet

      - name: Build and Push All Service Images
        run: |
          REGION=asia-east1  # or your chosen region
          REPOSITORY=email-noti-service # your repo name
          for SERVICE in $SERVICES; do
            DOCKERFILE="devops/docker/Dockerfile-$SERVICE"
            IMAGE="$REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPOSITORY/email-notification-$SERVICE:$IMAGE_TAG"
            BUILD_VERSION="$IMAGE_TAG"
            BUILD_COMMIT_HASH="$IMAGE_TAG"
            BUILD_TIME="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            echo "Building $SERVICE using $DOCKERFILE as $IMAGE"
            docker build -f $DOCKERFILE \
              --build-arg BUILD_VERSION=$BUILD_VERSION \
              --build-arg BUILD_COMMIT_HASH=$BUILD_COMMIT_HASH \
              --build-arg BUILD_TIME="$BUILD_TIME" \
              -t $IMAGE .
            docker push $IMAGE
          done